name: build

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install GTest on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get install -y libgtest-dev
  
      - name: Install GTest on macOS
        if: startsWith(matrix.os, 'macos')
        run: brew install gtest
            
      - name: hakoniwa-px4sim/hakoniwa
        run: |
          cd hakoniwa && bash build.bash
