name: Build

on: 
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build hakoniwa-px4sim/drone_physics on ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
            cd drone_physics && cmake -D HAKO_CLIENT_OPTION_FILEPATH=../cmake-options/linux-cmake-options.cmake . && make

      - name: Build hakoniwa-px4sim/drone_physics on macOs
        if: startsWith(matrix.os, 'macos')
        run: |
            cd drone_physics && cmake . && make
  

      - name: hakoniwa-px4sim/hakoniwa
        run: |
          cd hakoniwa && bash build.bash

