name: Test

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install GTest on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get install -y libgtest-dev
  
      - name: Install GTest on macOS
        if: startsWith(matrix.os, 'macos')
        run: brew install googletest

      - name: Run Tests/drone_physics
        run: |
          cd drone_physics && make run_verbose_test
        
      - name: Run Tests/hakoniwa
        run: |
          cd hakoniwa/cmake-build && test/hako-px4sim-test
